### ISSUE TITLE
Searching FAQ questions is broken

### ISSUE THREAD

**Issue by cartogram** [studio-cartogram/fondfolio-home#6]
<img width="1666" alt="Screen Shot 2020-11-15 at 17 50 18" src="https://user-images.githubusercontent.com/462077/99191159-22936100-276b-11eb-8aa7-3ecca98db8ac.png">

**Comment by feeohnah** [comment]
fixed 6eee99a3737ecc7b59ef26a903fb5a0b0a4de5fa
